force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Current_CTC__c.field-meta.xml
<CustomField>
    <fullName>Current_CTC__c</fullName>
    <label>Current CTC</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Banglore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hydrabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Vizay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MixedDMLExeption.cls
public class MixedDMLExeption 
{
Public static void DoDMLOperations()
    {
        // De-Activate the User (Setup Object)
        	User userInfo = [Select ID, FirstName, LastName, title, UserName, isActive
                            				from User
                            					Where UserName = 'dmahesh@gmail.com'];
        	if(userInfo.id != Null)
            {
                userInfo.IsActive = true;
                userInfo.Username = '	dmahesh12@gmail.com';
                Update userInfo;
                
                // Call the Method...
                CreateHiringManagerRecord();
            }
    }
    
    @future()
    Public static void CreateHiringManagerRecord()
    {
        // Create a New Hiring Manager Record. (Non-Setup Object)
        	Hiring_Manager__c hrRecord = new Hiring_Manager__c();
        
        		hrRecord.Name = 'Test Record';
        		hrRecord.Location__c = 'Vizag';
        		hrRecord.Email_Address__c = 'test@gmail.com';
        	//	hrRecord.Employment_Type__c = 'Permanent';
        	//	hrRecord.Designation__c = 'HR Executive';
        		hrRecord.Current_CTC__c = 1200000;
        		hrRecord.Contact_Number__c = '9900336672';
        
        	Insert hrRecord;
        
        	if(hrRecord.Id != Null)
                System.debug('Hiring Manager Record Inserted Successfully.'+ hrRecord.Id);
    }
}