force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Desigination__c.field-meta.xml
<CustomField>
    <fullName>Desigination__c</fullName>
    <label>Desigination</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>HR Executive</fullName>
            </value>
            <value>
                <fullName>HR manager</fullName>
            </value>
            <value>
                <fullName>Requirements special list</fullName>
            </value>
            <value>
                <fullName>Sr.Executive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Banglore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hydrabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Vizay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/position__c/position__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the requirements of the position.</description>
    <label>position</label>
    <nameField>
        <label>position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Hiring_Manager__c.Location__c</field>
            <operation>equals</operation>
            <valueField>$Source.Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Hiring_Manager__c</referenceTo>
    <relationshipLabel>positions</relationshipLabel>
    <relationshipName>positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bandar</fullName>
            </value>
            <value>
                <fullName>Banglore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hydrabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SOQLstaticexample1.cls
public class SOQLstaticexample1 
{
    Public static void childparentcustomrecords()
    {
        List<Hiring_manager__c>  Hrrecord =[Select Id, Name, Location__c, Contact_Number__c,Email_Address__C,Desigination__C, 
                                            (Select Name, Location__c from positions__r)
								                     from Hiring_Manager__c 
                                                             Where Name ='bablu'];  
        
        
            
      
    }
    public static void childparentstandardrecords()
    {
        Case csrecord =[select id, caseNumber, Status, Priority, origin, reason, subject,
                              Contact.FirstName, Contact.LastName, Contact.email,
                                Contact.Account.Name, Contact.Account.Rating, Contact.Account.Industry,
                                   Contact.Account.Owner.FirstName, Contact.Account.Owner.LastName,
                                       Contact.Account.Owner.Profile.Name,
                                          Contact.Account.Owner.Profile.UserLicense.Name
                                     from case
                                         Where CaseNumber ='00001004'];
        System.debug(csrecord.id);
        System.debug(csrecord.CaseNumber);
        System.debug(csrecord.Status);
        System.debug(csrecord.priority);
        System.debug(csrecord.Subject);
        System.debug(csrecord.Origin);
        System.debug(csrecord.Contact.FirstName+ ' ' + csrecord.Contact.LastName);
        System.debug(csrecord.Contact.email);
        System.debug(csrecord.Contact.Account.Name);
        
    }
    Public static void GetLeadRecords()
    {       
            for(Lead ldRecord : [Select Id, FirstName, LastName, Title, Company, Status, Rating,
                              					Industry, Phone, Fax, Email
                              							from Lead])
            {
                System.debug('Lead Record Id is.....: '+ ldRecord.Id);
                System.debug('Lead Person Name is....: '+ ldRecord.FirstName + ' '+ ldRecord.LastName);
                System.debug('Company Name is.....: '+ ldRecord.Company);
                System.debug('Lead Status is......: '+ ldRecord.Status);
                System.debug('Contact Number is....: '+ ldRecord.Phone);
                System.debug('Email Address is.....: '+ ldRecord.Email);
                System.debug('Lead Title is......: '+ ldRecord.Title);
				System.debug('Industry Name is.....: '+ ldRecord.Industry);
                System.debug('----------------------------------------------');
            }
        
        	System.debug('Number of SOQL Queries used.....: '+ System.Limits.getQueries());
        	System.debug('Number of Records Returned......: '+ System.Limits.getQueryRows());
    }
    public static void parentchildstandardRecords(string accountRecordName) 
    {
        if(accountRecordName != Null && accountRecordName != '')
        {
            List<Account> lstAccounts = [Select Id, Name, Rating, Industry, AnnualRevenue, Phone, Fax, Active__c,
                                            (Select ID, FirstName, LastName, Email, Title, Phone from Contacts),
                                                (Select Id, Name, Amount, CloseDate, StageName, Probability from Opportunities),
                                                    (Select ID, CaseNumber, Status, Priority, Origin, Reason from Cases)
                                                        from Account
                                                            Where Name =: accountRecordName];

            System.debug('Number of Matching Account Records Found....: '+ lstAccounts.Size());

            for(Account accRecord : lstAccounts)
            {
                System.debug('Account Name is......: '+ accRecord.Name);
                System.debug('Rating Value is......: '+ accRecord.Rating);
                System.debug('Industry Name is.....: '+ accRecord.Industry);
                System.debug('Annual Revenue is....: '+ accRecord.AnnualRevenue);
                System.debug('Contact Number is....: '+ accRecord.Phone);
                System.debug('Fax Number is........: '+ accRecord.Fax);
                System.debug('Active Status is.....: '+ accRecord.Active__c);

                System.debug('----------------------------------------------');
                List<Contact> lstContacts = accRecord.Contacts;
                System.debug('Number of Related Contacts.....: '+ lstContacts.Size());
                    for(Contact conRecord : lstContacts)
                    {
                        System.debug('Contact Record is.....: '+ conRecord);
                    }
                
                System.debug('-----------------------------------------------');
                List<Opportunity> lstOppty = accRecord.Opportunities;
                System.debug('Number of Related Opportunities.....: '+ lstOppty.Size());
                    for(Opportunity oppty : lstOppty)
                    {
                        System.debug('Opportunity Record is...: '+ oppty);
                    }

                System.debug('----------------------------------------------');
                System.debug('Number of Related Cases......: '+ accRecord.Cases.Size());
                    for(Case csRecord : accRecord.Cases)
                    {
                        System.debug('Case Record is......: '+ csRecord);
                    }
            }
        }

        System.debug('Number of SOQL Queries used......: '+ System.Limits.getQueries());
    }  
    public static void meth1()
    {
        List<Task> relatedTasks = [SELECT Id, Subject, ActivityDate, Status 
                           FROM Task 
                           ];
        system.debug(relatedTasks);

    }
}